### ISSUE TITLE
Test package collides with stuff from other libraries

### ISSUE THREAD

**Issue by rjoyce** [Juniper/py-space-platform#49]
Hi Roshan,
I have downloaded and installed the SpaceEZ 1.0.0 platform from github. 
I am not able to run the code unless I create/link a file named pkg_level_logging.conf.  
Here is error message:
subratam-mbp15:py-space-apps subratam$ python ./device_mgmt.py --dev-cmd rpc 
Traceback (most recent call last):
  File "./device_mgmt.py", line 1254, in <module>
    sys.exit(main())
  File "./device_mgmt.py", line 1189, in main
    deviceManager.login()
  File "./device_mgmt.py", line 135, in login
    self.space = rest.Space(url, user, passwd, use_session=True)
  File "/Library/Python/2.7/site-packages/jnpr/space/rest.py", line 131, in __init__
    self.login(required_node)
  File "/Library/Python/2.7/site-packages/jnpr/space/rest.py", line 421, in login
    from jnpr.space import connection
  File "/Library/Python/2.7/site-packages/jnpr/space/connection.py", line 26, in <module>
    standard_library.install_aliases()
  File "/Library/Python/2.7/site-packages/future/standard_library/__init__.py", line 482, in install_aliases
    import test
  File "/Library/Python/2.7/site-packages/test/__init__.py", line 21, in <module>
    logging.config.fileConfig('./pkg_level_logging.conf')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/config.py", line 70, in fileConfig
    formatters = _create_formatters(cp)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/config.py", line 106, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'formatters'
subratam-mbp15:py-space-apps subratam$ 

Here are my import statements:
import sys
import traceback
import re
import os.path
from pprint import pprint, pformat

from lxml import etree
import tempfile
import difflib
import subprocess

import ConfigParser
import time
import requests
import urllib

import logging.config
from jnpr.space import rest, factory, async, resource, xmlutil

Please let me know if configured something wrong.
Thanks.
—
Subrata

**Comment by rjoyce** [comment]
Fixed via commit ee43f20a0d7d6ea1136d61f7777c4cf96eddf74d
